### ISSUE TITLE
Unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Iristyle** [fabiokr/sublime-related-files#2] opened 2013-03-08 03:58 UTC
```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 339, in run_
  File ".\related_files.py", line 14, in run
  File ".\related.py", line 22, in __init__
  File ".\related.py", line 42, in __build
  File ".\related.py", line 61, in __files_for_paths
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by fabiokr** [comment] 2013-03-08 10:56
What is your Sublime version?

**Comment by Iristyle** [comment] 2013-03-08 12:55
`2.0.1, Build 2217` - Windows 8 x64

**Comment by Iristyle** [comment] 2013-03-08 13:01
Also... I've been adding a little logging to try to deduce what's going on.  Python isn't one of my stronger languages ... but ... 

On an unrelated note:

I don't think I see any path normalizing going on for 

``` python
active_file_path = self.__active_file_path()
```

So on Windows, I'll get Windows style paths with `C:\`, etc .. instead of a path like `C:/`.  That means that any default regexs won't work.  Again, not a Python guy, so I might have missed it, but I think it would make sense to normalize the path, with something like this.  Then the regex definitions from `RelatedFiles.sublime-settings` can just use `/` and be OS agnostic.

``` python
active_file_path = re.sub(r'\\', '/', active_file_path)
```

I'm sure Sublime or Python probably already has something built-in to do the above...

If you want me to add that as a separate issue, I can do that...

**Comment by fabiokr** [comment] 2013-03-08 13:09
Ah sure, that is probably the root cause. I added #2 to look at that. I'll take a look at it soon, thanks!

**Comment by Iristyle** [comment] 2013-03-08 14:36
FYI -- I've also tried both path styles in my Regex config (including with / without my normalization code above), but I'm still not getting matches.

Unlike Python, I'm pretty comfortable with regexs, and have verified that my expressions are matching what I've logged for the path, so I believe the issue is elsewhere.

If I can get to it later today, I'll really start to dig into your code to figure it out...

**Comment by fabiokr** [comment] 2013-03-10 23:28
Pushed a fix on master. Can you give it a shot?

**Comment by Iristyle** [comment] 2013-03-11 12:08
Excellent -- seems to be working now.  Let me throw a few more tests at it, but looks like we're good now.

Thanks!

**Closed as completed** 2013-03-12 01:35 UTC
